version: '3'
services:
  desafio:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST: localhost
      PORT: 5432
      USER_DB: postgres
      PASSWORD_DB: postgres
      DB_NAME: v3_development
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - desafio_network

  db:
    image: postgres:14
    container_name: my_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - desafio_network

networks:
  desafio_network: